### ISSUE TITLE
Implemention Like Rails Scaffolding?

### ISSUE THREAD

**Issue by NexusMTO** [rw3iss/nestjs-gen#2]
Congratulations on your library!!

There will be an implementation to create columns of the entity style rails?

similar

`rails g scaffolding User id:integer name:string username:string:unique email:string password:string`

ngen 

`ngen User --all id:number  name:string username:string:unique email:string password:string `

generation:

```
#user.model.ts

import { Entity, PrimaryGeneratedColumn, Column } from "typeorm";

@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column({ unique: true })
    username: string;

    @Column()
    email: string;

    @Column()
    password: string;

}
```

**Comment by rw3iss** [comment]
It's not that hard to add this functionality, and maybe I could, but I don't necessarily want to pollute the CLI commands with a bunch of custom object definitions. The point of the CLI tool here is to generate the basic file layouts and injections. The actual (possibly) custom class definitions an be implemented in the files after generation easily enough. It takes nearly the same effort

**Comment by rw3iss** [comment]
Well, it's not hard to add this, but don't necessarily want to pollute the CLI namespace with custom definitions so much. Can generally open the generated file to add the custom bits, by design.
However, it's not a bad feature, and useful, and I can try to implement it, but the CLI program interface package I use (caporal) doesn't seem to have a way to support arbitrary or anonymous arguments, so finding it tough to get the custom arguments ("name:type") initially fed into the program, but I'll see if there's a way around this somehow. It could work with an approach like "ngen User -a --props prop:type -p prop:type" or otherwise put all the property definitions into one argument, ie.:  ngen User -a --props "prop: type prop:type ..." so then could all be parsed by the '--props' argument value.... so I'll try something like this for now maybe.

**Comment by rw3iss** [comment]
I think instead what I'll do, for now, is make the model property definitions a value of the "--model" argument, as is... and optional.

So can write:

ngen user -a --model "prop:type prop:type" 

This is probably preferred because it also tells the CLI to actually generate a model, which would be required if passing a model definition string as such.

**Comment by rw3iss** [comment]
Hi @ZephiroRB 

I've implemented this basically in the most recent version, please see the readme:
[](https://github.com/rw3iss/nestjs-gen#specifying-model-properties-optional)

It will support adding propName:propType in the --model value, but won't add any custom decorators, joins, unique keys, etc... which will take a good bit more logic to figure out, so for now, hopefully the generated model file suffices, and you can customize it after it's generated.
